//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LineBreakFixupsDemo.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public string SuccessfulOutcomeMessageColor {
            get {
                return ((string)(this["SuccessfulOutcomeMessageColor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Green")]
        public string SuccessfulOutcomeMessageBackgroundColor {
            get {
                return ((string)(this["SuccessfulOutcomeMessageBackgroundColor"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\..\\Test_Data")]
        public string DATA_DIRECTORY_NAME {
            get {
                return ((string)(this["DATA_DIRECTORY_NAME"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("strResponse_Raw_20190508_181920_Windows_LineBreaks.JSON")]
        public string JSON_INPUT_FILE_NAME_WINDOWS {
            get {
                return ((string)(this["JSON_INPUT_FILE_NAME_WINDOWS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("strResponse_Intermediate_Windows_LineBreaks_Raw.TXT")]
        public string JSON_INTERMEDIATE_FILE_NAME_WINDOWS_RAW {
            get {
                return ((string)(this["JSON_INTERMEDIATE_FILE_NAME_WINDOWS_RAW"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("strResponse_FINAL_Windows_LineBreaks_Raw.TXT")]
        public string JSON_FINAL_FILE_NAME_WINDOWS_RAW {
            get {
                return ((string)(this["JSON_FINAL_FILE_NAME_WINDOWS_RAW"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("strResponse_Contents_Windows_LineBreaks_Raw.TXT")]
        public string JSON_CONTENTS_REPORT_FILE_NAME_WINDOWS_RAW {
            get {
                return ((string)(this["JSON_CONTENTS_REPORT_FILE_NAME_WINDOWS_RAW"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("strResponse_Raw_20190508_181920_Unix_LineBreaks.JSON")]
        public string JSON_INPUT_FILE_NAME_UNIX {
            get {
                return ((string)(this["JSON_INPUT_FILE_NAME_UNIX"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("strResponse_Intermediate_Unix_LineBreaks.TXT")]
        public string JSON_INTERMEDIATE_FILE_NAME_UNIX {
            get {
                return ((string)(this["JSON_INTERMEDIATE_FILE_NAME_UNIX"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("strResponse_FINAL_Unix_LineBreaks.TXT")]
        public string JSON_FINAL_FILE_NAME_UNIX {
            get {
                return ((string)(this["JSON_FINAL_FILE_NAME_UNIX"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("strResponse_Contents_Unix_LineBreaks.TXT")]
        public string JSON_CONTENTS_REPORT_FILE_NAME_UNIX {
            get {
                return ((string)(this["JSON_CONTENTS_REPORT_FILE_NAME_UNIX"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("strResponse_Intermediate_Windows_LineBreaks_Transformed.TXT")]
        public string JSON_INTERMEDIATE_FILE_NAME_WINDOWS_TRANSFORMED {
            get {
                return ((string)(this["JSON_INTERMEDIATE_FILE_NAME_WINDOWS_TRANSFORMED"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("strResponse_FINAL_Windows_LineBreaks_Transformed.TXT")]
        public string JSON_FINAL_FILE_NAME_WINDOWS_TRANSFORMED {
            get {
                return ((string)(this["JSON_FINAL_FILE_NAME_WINDOWS_TRANSFORMED"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("strResponse_Contents_Windows_LineBreaks_Transformed.TXT")]
        public string JSON_CONTENTS_REPORT_FILE_NAME_WINDOWS_TRANSFORMED {
            get {
                return ((string)(this["JSON_CONTENTS_REPORT_FILE_NAME_WINDOWS_TRANSFORMED"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Application_Settings_Report.TSV")]
        public string APP_SETTINGS_REPORT_FILENAME {
            get {
                return ((string)(this["APP_SETTINGS_REPORT_FILENAME"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Embedded_Resources_Report.TSV")]
        public string EMBEDDED_RESOURCES_REPORT_FILENAME {
            get {
                return ((string)(this["EMBEDDED_RESOURCES_REPORT_FILENAME"]));
            }
        }
    }
}
