/*
    ============================================================================

    Namespace:			LineBreakFixupsDemo

    Class Name:			TimeSeriesDailyResponse

	File Name:			TimeSeriesDailyResponse.cs

    Synopsis:			This static class exposes helper methods used by unit
                        test class LineEndingFixupTests.

    Author:				David A. Gray

	License:            Copyright (C) 2019, David A. Gray.
						All rights reserved.

                        Redistribution and use in source and binary forms, with
                        or without modification, are permitted provided that the
                        following conditions are met:

                        *   Redistributions of source code must retain the above
                            copyright notice, this list of conditions and the
                            following disclaimer.

                        *   Redistributions in binary form must reproduce the
                            above copyright notice, this list of conditions and
                            the following disclaimer in the documentation and/or
                            other materials provided with the distribution.

                        *   Neither the name of David A. Gray, nor the names of
                            his contributors may be used to endorse or promote
                            products derived from this software without specific
                            prior written permission.

                        THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND
                        CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED
                        WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
                        WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
                        PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
                        David A. Gray BE LIABLE FOR ANY DIRECT, INDIRECT,
                        INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
                        (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
                        SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
                        PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
                        ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
                        LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
                        ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
                        IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

    ----------------------------------------------------------------------------
    Revision History
    ----------------------------------------------------------------------------

    Date       Version By  Synopsis
    ---------- ------- --- -----------------------------------------------------
	2019/06/05 1.0     DAG Class copied from JSON_Jam project, replacing the
                           namespace, and adding this flower box, but otherwise
                           leaving it as is.
    ============================================================================
*/

namespace LineBreakFixupsDemo
{
    //  ------------------------------------------------------------------------
    //  This class was generated by a tool.
    //
    //  It was created by using the Paste Special tool on the Edit menu of the
    //  Visual Studio 2017 code editor to generate a class from a JSON string.
    //  Apart from adding this flower box, the only edit was the substitution of
    //  Rootobject with TimeSeriesDailyResponse, since we cannot afford to have
    //  all such objects in a namespace called Rootobject. (There is already one
    //  other object that was generated in this way in StockTickerSparklines.
    //  ------------------------------------------------------------------------

    public class TimeSeriesDailyResponse
    {
        public Meta_Data Meta_Data
        {
            get; set;
        }
        public Time_Series_Daily [ ] Time_Series_Daily
        {
            get; set;
        }
    }   // public class TimeSeriesDailyResponse

    public class Meta_Data
    {
        public string Information
        {
            get; set;
        }
        public string Symbol
        {
            get; set;
        }
        public string LastRefreshed
        {
            get; set;
        }
        public string OutputSize
        {
            get; set;
        }
        public string TimeZone
        {
            get; set;
        }
    }   // public class Meta_Data

    public class Time_Series_Daily
    {
        public string Activity_Date
        {
            get; set;
        }
        public string Open
        {
            get; set;
        }
        public string High
        {
            get; set;
        }
        public string Low
        {
            get; set;
        }
        public string Close
        {
            get; set;
        }
        public string AdjustedClose
        {
            get; set;
        }
        public string Volume
        {
            get; set;
        }
        public string DividendAmount
        {
            get; set;
        }
        public string SplitCoefficient
        {
            get; set;
        }
    }   // public class Time_Series_Daily
}   // partial namespace LineBreakFixupsDemo